### ISSUE TITLE
Don't use `auth` if it's not DSAuth

### ISSUE THREAD

**Issue by nmushegian** [makerdao/vote-proxy#7]
Room for opinion on this one, but seems like a strong convention.

We could use onlyHot, onlyCold, hotOrCold

**Comment by nmushegian** [comment]
Incidentally, the convergent solution seems to use hotOrCold for everything, which is equivalent to multi-owner, which is the future direction of DSAuth. Still suggest not using the modifier name in this case.

**Comment by d-xo** [comment]
we already use `auth` without `ds-auth` all over `dss`, not sure that it's exclusive to `ds-auth` anymore.

**Comment by nmushegian** [comment]
ok =[

**Comment by nmushegian** [comment]
But maybe we shouldn't
